### ISSUE TITLE
Can't find bridge in release build

### ISSUE THREAD

**Issue by hojberg** [smore-inc/react-native-segment-io-analytics#12]
When trying to do a release build I get this build error:

<img width="649" alt="screen shot 2015-12-30 at 4 34 27 pm" src="https://cloud.githubusercontent.com/assets/2371/12052834/39b3e6be-af13-11e5-92c5-d4ce4dce9e0f.png">

**Comment by yelled3** [comment]
@talkain /cc

**Comment by talkain** [comment]
@hojberg Did you use the ```react-native init AwesomeApp``` command to initialize your project?

**Comment by hojberg** [comment]
@talkain yes i did, though since using cocoapods, i'm now using the workspace file

**Comment by etaiklein** [comment]
Hi there! Did you find a solution for this?

**Comment by talkain** [comment]
@etaiklein, Thanks for the comment, I added this to the search path.

@hojberg, If this is still an issue, I think this is because you are trying to compile the project without putting it inside a react-native project's node_modules (The project itself does not contain the react native bridge module headers, it suppose to be added and compiled with a react-native project)

Hope this helps..

**Comment by hojberg** [comment]
I moved on to a manual bridge - I havent looked at this in a while, sorry.
